apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: radial/busyboxplus:curl
    name: busybox
    args:
    - sleep
    - "1000000"
