apiVersion: v1
kind: Service
metadata:
  labels:
    app: supersecret
  name: supersecret
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30084
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: supersecret
  type: NodePort
