apiVersion: apps/v1
kind: Deployment
metadata:
  name: supersecret
  labels:
    app: supersecret
spec:
  selector:
    matchLabels:
      app: supersecret
  template:
    metadata:
      labels:
        app: supersecret
    spec:
      containers:
      - name: supersecret
        # Use your repository for supersecretmessage here
        image: localhost:32000/supersecret
        ports:
        - containerPort: 8082
        env:
        - name: VAULT_ADDR
          value:  "http://vault:8200"
        - name: VAULT_TOKEN
          value:  "supersecret"
        - name: SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS
          value: ":8082"

