apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      containers:
      - image: vault:latest
        name: vault
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "supersecret"
        securityContext:
            capabilities:
              add: ["IPC_LOCK"]
